services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: proyectofinal-backend-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      # Como ya no es "host", usamos la IP de la máquina AWS para conectar al MySQL nativo
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.17.0.1:3306/ProyectoTFG
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proyectofinal-frontend-container
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend