spring.application.name=backend
#DATABASE CONFIGURACION
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/ecomercedzz
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true


#Security Config
#spring.security.user.name=Duzz
#spring.security.user.password=1234

#Clave secreta generada en: https://tools.keycdn.com/sha256-online-generator
security.jwt.key.private= 3629555f0a4fd3c7916a247b548671c078717483a2e6d0a524daeb40d5b622b2
#Creamos el usuario generador del token
security.jwt.user.generator= DUZZ-BACKEND